repos:
  - repo: local
    hooks:
      - id: docuhook
        name: DocuHook - Auto-generate Docstrings
        entry: python docuhook/main.py
        language: system
        stages: [pre-commit]
        files: \.py$
